# Generated by Django 3.2.9 on 2021-12-19 15:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(default=None, max_length=1024, null=True, verbose_name='买家')),
                ('address', models.CharField(default=None, max_length=1024, null=True, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=15, unique=True, verbose_name='账号')),
                ('pwd', models.CharField(max_length=20, verbose_name='密码')),
                ('birth', models.DateField(default=None, null=True, verbose_name='生日')),
                ('email', models.EmailField(default=None, max_length=254, null=True, verbose_name='邮箱')),
                ('nickname', models.CharField(max_length=16, null=True, verbose_name='昵称')),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], default=None, null=True, verbose_name='性别')),
                ('balance', models.IntegerField(default=0, null=True, verbose_name='余额')),
                ('Preference', models.CharField(default=None, max_length=1024, null=True, verbose_name='偏好')),
                ('state', models.IntegerField(choices=[(0, '正常'), (1, '冻结')], default=None, null=True, verbose_name='状态')),
                ('Address', models.TextField(default=None, null=True, verbose_name='地址')),
                ('headimg', models.ImageField(null=True, upload_to='img/', verbose_name='头像')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default=None, max_length=1024, null=True, verbose_name='楼主')),
                ('title', models.CharField(default=None, max_length=1024, null=True, verbose_name='标题')),
                ('details', models.TextField(default=None, max_length=1024, null=True, verbose_name='详情')),
                ('time', models.DateField(default=None, null=True, verbose_name='下单时间')),
                ('content', ckeditor.fields.RichTextField(null=True, verbose_name='正文内容')),
            ],
        ),
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=254, null=True, verbose_name='邮箱')),
                ('code', models.CharField(default=None, max_length=128, verbose_name='验证码')),
            ],
        ),
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=128, null=True, verbose_name='商品名')),
                ('label', models.CharField(default=None, max_length=1024, null=True, verbose_name='标签')),
                ('inventory', models.CharField(default=None, max_length=128, null=True, verbose_name='库存')),
                ('price', models.CharField(default=None, max_length=128, null=True, verbose_name='价格')),
                ('details', models.TextField(default=None, max_length=1024, null=True, verbose_name='详情')),
                ('seller', models.CharField(default=None, max_length=1024, null=True, verbose_name='卖家')),
                ('comments', models.CharField(default=None, max_length=128, null=True, verbose_name='评论')),
                ('state', models.IntegerField(default=0, null=True, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default=None, max_length=1024, null=True, verbose_name='标签')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.CharField(default=None, max_length=1024, null=True, verbose_name='商品')),
                ('buyer', models.CharField(default=None, max_length=1024, null=True, verbose_name='买家')),
                ('seller', models.CharField(default=None, max_length=1024, null=True, verbose_name='卖家')),
                ('receiving_address', models.CharField(default=None, max_length=1024, null=True, verbose_name='收货地址')),
                ('number', models.IntegerField(default=None, null=True, verbose_name='数量')),
                ('price', models.IntegerField(default=None, null=True, verbose_name='价格')),
                ('time', models.DateField(default=None, null=True, verbose_name='下单时间')),
                ('state', models.IntegerField(default=0, null=True, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='orderGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsID', models.IntegerField(null=True, verbose_name='商品')),
                ('orderID', models.IntegerField(null=True, verbose_name='订单')),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=15, unique=True, verbose_name='账号')),
                ('pwd', models.CharField(max_length=20, verbose_name='密码')),
                ('birth', models.DateField(default=None, null=True, verbose_name='生日')),
                ('email', models.EmailField(default=None, max_length=254, null=True, verbose_name='邮箱')),
                ('nickname', models.CharField(max_length=16, null=True, verbose_name='昵称')),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], default=None, null=True, verbose_name='性别')),
                ('balance', models.CharField(default=0, max_length=16, verbose_name='余额')),
                ('Preference', models.CharField(default=None, max_length=1024, null=True, verbose_name='偏好')),
                ('state', models.IntegerField(choices=[(0, '正常'), (1, '冻结')], default=None, null=True, verbose_name='状态')),
                ('address', models.TextField(default=None, null=True, verbose_name='地址')),
                ('headimg', models.ImageField(null=True, upload_to='img/', verbose_name='头像')),
            ],
        ),
        migrations.CreateModel(
            name='shoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.CharField(default=None, max_length=1024, null=True, verbose_name='商品')),
                ('buyer', models.CharField(default=None, max_length=1024, null=True, verbose_name='买家')),
                ('price', models.IntegerField(default=None, null=True, verbose_name='价格')),
            ],
        ),
    ]
