# Generated by Django 3.2.9 on 2021-12-19 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shoppingCart',
        ),
    ]
