# Generated by Django 3.2.9 on 2021-12-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0004_auto_20211219_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='goods',
            field=models.CharField(default=None, max_length=1024, null=True, verbose_name='商品'),
        ),
    ]
