# Generated by Django 3.2.9 on 2021-12-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0005_shoppingcart_goods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='goods',
            new_name='good',
        ),
    ]
