# Generated by Django 3.2.9 on 2021-12-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0008_auto_20211219_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='inventory',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='库存'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='title',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='商品名'),
        ),
    ]
