# Generated by Django 3.2.9 on 2021-12-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0010_order_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='img',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='图片'),
        ),
    ]
