# Generated by Django 3.2.9 on 2021-12-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0011_goods_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to='img/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='inventory',
            field=models.IntegerField(default=None, null=True, verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.IntegerField(default=None, null=True, verbose_name='价格'),
        ),
    ]
